fix missing blazesym head file
There're some updates in Makefile in commit 4b207312dd. But it's not
synchronized into CMakeLists.txt. It causes the error in below.

 77%] Building C object CMakeFiles/profile.dir/profile.c.o
libbpf-bootstrap/examples/c/profile.c:17:10: fatal error: blazesym.h: No such file or directory
   17 | #include "blazesym.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/profile.dir/build.make:84: CMakeFiles/profile.dir/profile.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:520: CMakeFiles/profile.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>